AllStarConsulting/AllStar.Website/Models/Job.cs
namespace AllStar.Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            Hours = new HashSet<Hour>();
            Tasks = new HashSet<JobTask>();
        }
        [Key]
        public int JobId { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [StringLength(20, ErrorMessage = "Must be less than 20 characters")]
        public string Name { get; set; }

        [Column(TypeName = "text")]
        [Required(ErrorMessage = "Description is required")]
        [StringLength(500, ErrorMessage = "Must be less than 500 characters")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Hourly wage is required")]
        [Range(0, 100, ErrorMessage = "Hourly wage must be less than 100")]
        [Display(Name = "Hourly Wage")]
        public decimal HourlyWage { get; set; }

        [Required(ErrorMessage = "Start date is required")]
        [DataType(DataType.Date, ErrorMessage = "Invalid Date.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Column(TypeName = "date")]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Invalid Date.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Column(TypeName = "date")]
        [Display(Name = "End Date")]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Completion")]
        public bool CompletedFlag { get; set; }
        
        [StringLength(50, ErrorMessage = "Must be less than 50 characters")]
        public string EmployeeName { get; set; }
        public string UserId { get; set; }
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hour> Hours { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobTask> Tasks { get; set; }
    }
}

AllStarConsulting/AllStar.Website/Controllers/HoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AllStar.Website.Models;
using NLog;

namespace AllStar.Website.Controllers
{
    public class HoursController : Controller
    {
        private AllStar_Database db = new AllStar_Database();
        private Logger logger = LogManager.GetCurrentClassLogger();

        // GET: Hours/Create
        public ActionResult Create(int jobId, int taskId)
        {
            Hour hour = new Hour();
            hour.JobId = jobId;
            hour.TaskId = taskId;
            hour.Date = DateTime.Today;
      
            return View(hour);
        }

        // POST: Hours/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobId,TaskId,HourId,Date,Hours")] Hour hour)
        {
            try
            { 
            if (ModelState.IsValid)
            {
                db.Hours.Add(hour);
                db.SaveChanges();
                    logger.Info($"{User.Identity.Name} created hours for {hour.Task.Name}");
                    return RedirectToAction("Edit", "Jobs", new { id = hour.JobId});
            }
            
            return View(hour);
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return new HttpStatusCodeResult(500);
            }
        }

        // GET: Hours/Edit/5
        public ActionResult Edit(int? id, int? jobId, int? taskId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hour hour = db.Hours.Find(jobId, taskId, id);
            if (hour == null)
            {
                return HttpNotFound();
            }
            return View(hour);
        }

        // POST: Hours/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobId,TaskId,HourId,Date,Hours")] Hour hour)
        {
            try
            { 
            if (ModelState.IsValid)
            {
                db.Entry(hour).State = EntityState.Modified;
                db.SaveChanges();
                    logger.Info($"{User.Identity.Name} edited hours for {hour.Task.Name}");
                    return RedirectToAction("Edit", "Jobs", new { id = hour.JobId });
            }
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "Name", hour.JobId);
            ViewBag.TaskId = new SelectList(db.Tasks, "TaskId", "Name", hour.TaskId);
            return View(hour);
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return new HttpStatusCodeResult(500);
            }
        }

        // GET: Hours/Delete/5
        public ActionResult Delete(int? id, int? jobId, int? taskId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hour hour = db.Hours.Find(jobId, taskId, id);
            if (hour == null)
            {
                return HttpNotFound();
            }
            return View(hour);
        }

        // POST: Hours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            { 
            Hour hour = db.Hours.Find(id);
            db.Hours.Remove(hour);
            db.SaveChanges();
                logger.Info($"{User.Identity.Name} deleted hours for {hour.Task.Name}");
                return RedirectToAction("Edit", "Jobs", new { id = hour.JobId });
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return new HttpStatusCodeResult(500);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AllStarConsulting/AllStar.Website/Controllers/JobTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AllStar.Website.Models;
using NLog;

namespace AllStar.Website.Controllers
{
    public class JobTasksController : Controller
    {
        private AllStar_Database db = new AllStar_Database();
        private Logger logger = LogManager.GetCurrentClassLogger();

        // GET: JobJobTasks/Create
        public ActionResult Create(int jobId)
        {
            JobTask job = new JobTask();
                job.JobId = (int)jobId;
            
            return View(job);
        }

        // POST: JobJobTasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskId,Name,Description,EstimatedHours,CompletedFlag,JobId")] JobTask jobTask)
        {
            try
            { 
            if (ModelState.IsValid)
            {
                db.Tasks.Add(jobTask);
                db.SaveChanges();
                    logger.Info($"{User.Identity.Name} created {jobTask.Name}");
                    return RedirectToAction("Edit", "Jobs", new { id = jobTask.JobId });
            }

            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "Name", jobTask.JobId);
            return View(jobTask);
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return new HttpStatusCodeResult(500);
            }
        }

        // GET: JobJobTasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobTask jobTask = db.Tasks.Find(id);
            if (jobTask == null)
            {
                return HttpNotFound();
            }
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "Name", jobTask.JobId);
            return View(jobTask);
        }

        // POST: JobJobTasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaskId,Name,Description,EstimatedHours,CompletedFlag,JobId")] JobTask jobTask)
        {
            try
            { 
            if (ModelState.IsValid)
            {
                db.Entry(jobTask).State = EntityState.Modified;
                db.SaveChanges();
                    logger.Info($"{User.Identity.Name} edited {jobTask.Name}");
                    return RedirectToAction("Edit", "Jobs", new { id = jobTask.JobId });
            }
            ViewBag.JobId = new SelectList(db.Jobs, "JobId", "Name", jobTask.JobId);
            return View(jobTask);
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return new HttpStatusCodeResult(500);
            }
        }

        // GET: JobJobTasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobTask jobTask = db.Tasks.Find(id);
            if (jobTask == null)
            {
                return HttpNotFound();
            }
            return View(jobTask);
        }

        // POST: JobJobTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
            JobTask jobTask = db.Tasks.Find(id);
            db.Tasks.Remove(jobTask);
            db.SaveChanges();
                logger.Info($"{User.Identity.Name} deleted {jobTask.Name}");
                return RedirectToAction("Edit", "Jobs", new { id = jobTask.JobId });
            }
            catch (Exception ex)
            {
                logger.Error(ex);
                return new HttpStatusCodeResult(500);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AllStarConsulting/AllStar.Website/Views/Jobs/Complete.cshtml
@model AllStar.Website.Models.Job

@{
    ViewBag.Title = "Complete";
}

<h2>Complete</h2>

<h3>Are you sure you want to complete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HourlyWage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HourlyWage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        @if (Model.CompletedFlag)
        {
            <dd>
                @Html.DisplayFor(model => model.EndDate)
            </dd>
        }
        else
        {
            <dd>
                <span>@DateTime.Today</span>
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.CompletedFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">

        @if (Model.CompletedFlag)
        {
            <input type="submit" value="Uncomplete" class="btn btn-default" />
        }
        else
        {
            <input type="submit" value="Complete" class="btn btn-default" />
        }|
        @Html.ActionLink("Back to List", "Index")
    </div>
    }
    

</div>

AllStarConsulting/AllStar.Website/Views/Jobs/Create.cshtml
@model AllStar.Website.Models.Job

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Job</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HourlyWage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HourlyWage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HourlyWage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AllStarConsulting/AllStar.Website/Views/Jobs/Delete.cshtml
@model AllStar.Website.Models.Job

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.UserId != null)
        {
            <dt>
                Name
            </dt>

            <dd>
                <span>@ViewBag.EmpName</span>
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HourlyWage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HourlyWage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompletedFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompletedFlag)
        </dd>

    </dl>


    <div>
        <div style="display: flex;">
            <h1>TASKS</h1>
        </div>
        <span class="fas fa-plus openTasks"> Show Tasks</span>
        <span class="fas fa-minus closeTasks"> Hide Tasks</span>
    </div>
    @if (Model.Tasks != null)
    {
        <table class="tasksAccordion">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Estimated Hours</th>
                <th>Completion</th>
                <th></th>
            </tr>
            @foreach (var item in Model.Tasks)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.EstimatedHours.ToString()
                    </td>
                    <td>
                        @if (item.CompletedFlag)
                        {
                            <span>COMPLETED</span>
                        }
                        else
                        {
                            <span>IN PROGRESS</span>
                        }
                    </td>
                    <td>
                        <span class="fas fa-plus openpanel"> Show Hours</span>
                        <span class="fas fa-minus closepanel"> Hide Hours</span>
                    </td>
                </tr>
                <tr class="accordion">
                    @if (item.Hours != null)
                    {
                        <td colspan="7">
                            <ul>
                                @foreach (var hour in item.Hours)
                                {
                                    TimeSpan timespan = TimeSpan.FromHours((double)hour.Hours);
                                    string output = timespan.ToString("h\\:mm");

                                    <li>@output on @hour.Date.ToString("MM/dd/yyyy")</li>
                                }
                            </ul>
                        </td>
                    }
                </tr>
            }
        </table>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
    $(function () {
        $(".accordion").hide();
        $(".closepanel").hide();
        $(".closeTasks").hide();
        $(".tasksAccordion").hide();
    });

    $(".openpanel").on("click", function () {
        $(this).hide();
        $(this).next().show();
        $(this).parent().parent().next().show();
    });
    $(".closepanel").on("click", function () {
        $(this).hide();
        $(this).prev().show();
        $(this).parent().parent().next().hide();
    });

    $(".openTasks").on("click", function () {
        $(this).hide();
        $(".closeTasks").show();
        $(".tasksAccordion").show();
    });
    $(".closeTasks").on("click", function () {
        $(this).hide();
        $(".openTasks").show();
        $(".tasksAccordion").hide();
    });
    </script>
}

AllStarConsulting/AllStar.Website/Views/Jobs/Edit.cshtml
@model AllStar.Website.ViewModels.JobInfo

@{
    ViewBag.Title = "Edit";

    bool isManager =
        Request.IsAuthenticated &&
        (User.IsInRole("Manager") || User.IsInRole("Admin"));
}

<h2>Edit</h2>
<style>
    table tr th {
        padding-right: 20px;
    }

    table tr td {
        padding-right: 20px;
    }
</style>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    SelectList employees = new SelectList(Model.Users, "Id", "EmployeeNumber");
<div class="form-horizontal">
    <h4>Job</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.JobId)
    @if (isManager)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HourlyWage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HourlyWage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HourlyWage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.UserId, employees, "(All)")
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>
    }
    else
    {
        <dl class="dl-horizontal">
            @if (Model.UserId != null)
            {
                <dt>
                    Name
                </dt>

                <dd>
                    <span>@ViewBag.EmpName</span>
                </dd>
            }

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.HourlyWage)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HourlyWage)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StartDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartDate)
            </dd>

            @if (Model.EndDate != null)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.EndDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.EndDate)
                </dd>
            }

            <dt>
                @Html.DisplayNameFor(model => model.CompletedFlag)
            </dt>

            <dd>
                @if (Model.UserId != null)
                {
                    <span>IN PROGRESS</span>
                }
                else if (Model.CompletedFlag)
                {
                    <span>COMPLETED</span>
                }
                else
                {
                    <span>NOT STARTED</span>
                }
            </dd>

        </dl>
    }

    <div>
        <div style="display: flex;">
            <h1>TASKS</h1>
            <button class="btn btn-primary">
                @Html.ActionLink("Add Task", "Create", "JobTasks", new { jobId = Model.JobId }, null)
            </button>
        </div>
        <span class="fas fa-plus openTasks"> Show Tasks</span>
        <span class="fas fa-minus closeTasks"> Hide Tasks</span>
    </div>

    @if (Model.Tasks != null)
    {
        <table class="tasksAccordion">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Estimated Hours</th>
                <th>Completion</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model.Tasks)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.EstimatedHours.ToString()
                    </td>
                    <td>
                        @if (item.CompletedFlag)
                        {
                            <span>COMPLETED</span>
                        }
                        else
                        {
                            <span>IN PROGRESS</span>
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Add Hours", "Create", "Hours", new { jobId = item.JobId, taskId = item.TaskId }, null)
                    </td>
                    <td>
                        <span class="fas fa-plus openpanel"> Show Hours</span>
                        <span class="fas fa-minus closepanel"> Hide Hours</span>
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "JobTasks", new { id = item.TaskId }, null)
                        @Html.ActionLink("Delete", "Delete", "JobTasks", new { id = item.TaskId }, null)
                    </td>
                </tr>
                <tr class="accordion">
                    @if (item.Hours != null)
                    {
                        <td colspan="7">
                            <ul>
                                @foreach (var hour in item.Hours)
                                {
                                    TimeSpan timespan = TimeSpan.FromHours((double)hour.Hours);
                                    string output = timespan.ToString("h\\:mm");

                                    <li>@output on @hour.Date.ToString("MM/dd/yyyy")</li>
                                    if (isManager) {
                                    @Html.ActionLink("Edit", "Edit", "Hours", new { id = hour.HourId, jobId = Model.JobId, taskId = item.TaskId }, new { JobId = item.JobId })
                                    @Html.ActionLink("Delete", "Delete", "Hours", new { id = hour.HourId, jobId = Model.JobId, taskId = item.TaskId }, new { JobId = item.JobId })
                                    }
                                }
                            </ul>
                        </td>
                    }
                </tr>
            }
        </table>
    }


    <div class="form-group" style="padding-top: 30px;">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {
            $(".accordion").hide();
            $(".closepanel").hide();
            $(".closeTasks").hide();
            $(".tasksAccordion").hide();
        });

        $(".openpanel").on("click", function () {
            $(this).hide();
            $(this).next().show();
            $(this).parent().parent().next().show();
        });
        $(".closepanel").on("click", function () {
            $(this).hide();
            $(this).prev().show();
            $(this).parent().parent().next().hide();
        });

        $(".openTasks").on("click", function () {
            $(this).hide();
            $(".closeTasks").show();
            $(".tasksAccordion").show();
        });
        $(".closeTasks").on("click", function () {
            $(this).hide();
            $(".openTasks").show();
            $(".tasksAccordion").hide();
        });
    </script>
}